#ifndef __ERROR_CODES_AND_DEFINES_H__
#define __ERROR_CODES_AND_DEFINES_H__

//ERROR CODES
#define ERROR_OK 0
#define ERROR_BAD_ARGUMENT_COUNT 1
#define ERROR_IN_FILE 2
#define ERROR_MALLOC 101
#define ERROR_NO_DATA_IN_FILE 102


//OTHER PROJECT DEFINES


#endif
