#ifndef __ERROR_CODES_AND_DEFINES_H__
#define __ERROR_CODES_AND_DEFINES_H__

//ERROR CODES
#define ERROR_IN_TOO_LARGE 100
#define ERROR_OK 0
#define ERROR_BAD_ARGUMENT_COUNT 3
#define ERROR_IN_FILE 1
#define ERROR_OUT_FILE 2
#define ERROR_NO_MORE_AVER 101
#define ERROR_NO_DATA_IN_FILE 102


//OTHER PROJECT DEFINES
#define MAX_ARRAY_SIZE 50


#endif
